### ISSUE TITLE
Error when clicking in the Friendship link

### ISSUE THREAD

**Issue by efrapp** [FSolM/ror-fb-clone#12]
<img width="1419" alt="Screen Shot 2019-09-14 at 11 33 46 AM" src="https://user-images.githubusercontent.com/698811/64911234-ab84b780-d6e4-11e9-817d-adaa452ae444.png">

**Comment by codingAngarita** [comment]
Unfortunately, I couldn't replicate this error I think the issue was caused by a database error, currently, the Friendship link behaves as expected.
![image](https://user-images.githubusercontent.com/44899916/64984209-ec690180-d887-11e9-82f9-d1b9e581cb94.png)
