### ISSUE TITLE
When I try to sign in

### ISSUE THREAD

**Issue by efrapp** [FSolM/ror-fb-clone#13]
<img width="997" alt="Screen Shot 2019-09-14 at 11 54 32 AM" src="https://user-images.githubusercontent.com/698811/64911383-b9d3d300-d6e6-11e9-9d60-8d70ec4a164e.png">

**Comment by codingAngarita** [comment]
## Solved
![image](https://user-images.githubusercontent.com/44899916/64983952-4fa66400-d887-11e9-97b5-d4d68ab4a482.png)
